Some improvements
Signed-off-by: Marcos Yacob <marcosyacob@gmail.com>

diff --git a/test/integration/suites/force-rotation-jwt-authority/06-fetch-jwt-svid b/test/integration/suites/force-rotation-jwt-authority/06-fetch-jwt-svid
--- a/test/integration/suites/force-rotation-jwt-authority/06-fetch-jwt-svid
+++ b/test/integration/suites/force-rotation-jwt-authority/06-fetch-jwt-svid
@@ -5,9 +5,9 @@ prepared_authority=$(docker compose exec -t -e SPIRE_SERVER_FFLAGS=forced_rotati
     localauthority jwt show -output json | jq -r .active.authority_id) || fail-now "Failed to fetch prepared JWT authority ID"
 
 svid_json=$(docker compose exec spire-agent ./bin/spire-agent \
-	api fetch jwt -audience aud -output json)
+    api fetch jwt -audience aud -output json) || fail-now "Failed to fetch JWT SVID"
 
-jwt_svid=$(echo $svid_json | jq -c '.[0].svids.[0].svid') || fail-now "Failed to fetch JWT SVID"
+jwt_svid=$(echo $svid_json | jq -c '.[0].svids[0].svid') || fail-now "Failed to parse JWT SVID"
 
 # Store JWT SVID for the next steps
 echo $jwt_svid > conf/agent/jwt_svid
@@ -20,7 +20,7 @@ if [[ $skid != $prepared_authority ]]; then
     fail-now "JWT SVID key ID does not match the prepared authority ID, got $skid, expected $prepared_authority"
 fi
 
-keys=$(echo $svid_json | jq -c '.[1].bundles.["spiffe://domain.test"] | @base64d | fromjson')
+keys=$(echo $svid_json | jq -c '.[1].bundles["spiffe://domain.test"] | @base64d | fromjson')
 
 retry_count=0
 max_retries=20
@@ -37,8 +37,8 @@ while [[ $retry_count -lt $max_retries ]]; do
         sleep 2
         # Re-fetch the JWT SVID and keys
         svid_json=$(docker compose exec spire-agent ./bin/spire-agent \
-            api fetch jwt -audience aud -output json)
-        jwt_svid=$(echo $svid_json | jq -c '.[0].svids[0].svid')
+            api fetch jwt -audience aud -output json) || fail-now "Failed to re-fetch JWT SVID"
+        jwt_svid=$(echo $svid_json | jq -c '.[0].svids[0].svid') || fail-now "Failed to parse re-fetched JWT SVID"
         keys=$(echo $svid_json | jq -c '.[1].bundles["spiffe://domain.test"] | @base64d | fromjson')
     fi
 done
@@ -48,4 +48,3 @@ if [[ $success == false ]]; then
 fi
 
 echo $keys | jq --arg kid $prepared_authority -e '.keys[] | select(.kid == $kid)' > /dev/null || fail-now "Prepared authority not found in JWT SVID bundle"
-
