Finish test case
Signed-off-by: Marcos Yacob <marcosyacob@gmail.com>

diff --git a/test/integration/suites/force-rotation-upstream-authority/09-verify-svid-rotation b/test/integration/suites/force-rotation-upstream-authority/09-verify-svid-rotation
--- a/test/integration/suites/force-rotation-upstream-authority/09-verify-svid-rotation
+++ b/test/integration/suites/force-rotation-upstream-authority/09-verify-svid-rotation
@@ -12,14 +12,12 @@ verify-svid() {
     local agent=$1
     local agent_dir=$2
 
-    docker compose exec -u 1001 -T "$agent" \
-        /opt/spire/bin/spire-agent api fetch x509 \
-        -socketPath /opt/spire/sockets/workload_api.sock \
-        -write /tmp || fail-now "x509-SVID check failed for $agent"
-
     docker compose exec -T "$agent" \
-        openssl verify -verbose -CAfile /opt/spire/conf/agent/non-tainted.pem \
-        -untrusted /tmp/svid.0.pem /tmp/svid.0.pem
+        /opt/spire/bin/spire-agent api fetch x509 \
+        -write $agent_dir || fail-now "x509-SVID check failed for $agent"
+
+    openssl verify -verbose -CAfile conf/server/new_upstream_ca.crt \
+        -untrusted ${agent_dir}/svid.0.pem ${agent_dir}/svid.0.pem
 }
 
 check-tainted-authorities() {
@@ -28,12 +26,7 @@ check-tainted-authorities() {
     local agent_dir=$3
 
     x509Authorities=$(fetch-x509-authorities "$server")
-
-    taintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == true)') || fail-now "Tainted authority not found"
-
-    nonTaintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == false)') || fail-now "Non-tainted authority not found"
-
-    echo "$nonTaintedFound" | jq -r .asn1 | base64 -d | openssl x509 -inform der > "$agent_dir/agent/non-tainted.pem"
+    echo "$x509Authorities" | jq '.[] | select(.tainted == true)' || fail-now "Tainted authority not found"
 
     RETRY_COUNT=0
 
@@ -45,7 +38,7 @@ check-tainted-authorities() {
             break
         else
             RETRY_COUNT=$((RETRY_COUNT + 1))
-            echo "Verification failed, retrying in $RETRY_DELAY seconds... ($RETRY_COUNT/$MAX_RETRIES)"
+	    log-debug "Verification failed, retrying in $RETRY_DELAY seconds... ($RETRY_COUNT/$MAX_RETRIES)"
             sleep $RETRY_DELAY
         fi
 
@@ -56,4 +49,5 @@ check-tainted-authorities() {
 }
 
 # Root
-check-tainted-authorities "spire-server" "spire-agent" "root"
+check-tainted-authorities "spire-server" "spire-agent" "conf/agent"
+
diff --git a/test/integration/suites/force-rotation-upstream-authority/11-verify-revoked-upstream-authority b/test/integration/suites/force-rotation-upstream-authority/11-verify-revoked-upstream-authority
--- a/test/integration/suites/force-rotation-upstream-authority/11-verify-revoked-upstream-authority
+++ b/test/integration/suites/force-rotation-upstream-authority/11-verify-revoked-upstream-authority
@@ -3,23 +3,16 @@
 MAX_RETRIES=10
 RETRY_DELAY=2 # seconds between retries
 
-fetch-active-authority() {
-    docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
-        /opt/spire/bin/spire-server localauthority x509 show -output json | jq -r .active.authority_id
-}
-
 validate-agent() {
     local agent=$1
     local retry_count=0
 
     while [[ $retry_count -lt $MAX_RETRIES ]]; do
-        docker compose exec -u 1001 -T $agent \
+        docker compose exec -T $agent \
             /opt/spire/bin/spire-agent api fetch x509 \
-            -socketPath /opt/spire/sockets/workload_api.sock \
-            -write /tmp || fail_now "x509-SVID check failed for $agent"
+            -write /opt/spire/conf/agent || fail-now "x509-SVID check failed for $agent"
 
-        local bundle_count=$(docker compose exec -T $agent \
-            openssl storeutl -noout -text -certs /tmp/bundle.0.pem | grep -c "Certificate:")
+        local bundle_count=$(openssl storeutl -noout -text -certs conf/agent/bundle.0.pem | grep -c "Certificate:")
         if [ $bundle_count -eq 1 ]; then
             log-debug "Validation successful for $agent: There is exactly one certificate in the chain."
             return 0
@@ -40,8 +33,7 @@ check_ski() {
     local agent=$1
     local old_authority=$2
 
-    local ski=$(docker compose exec -T $agent \
-	    openssl x509 -in /tmp/bundle.0.pem -text | grep \
+    local ski=$(openssl x509 -in conf/agent/bundle.0.pem -text | grep \
 	    -A 1 'Subject Key Identifier' | tail -n 1 | tr -d ' ' | tr -d ':' | tr '[:upper:]' '[:lower:]')
 
     if [ "$ski" == "$old_authority" ]; then
@@ -51,11 +43,12 @@ check_ski() {
     fi
 }
 
-active_authority=$(fetch-active-authority)
-log-debug "Active authority: $active_authority"
+activeUpstreamAuthority=$(docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation spire-server \
+      /opt/spire/bin/spire-server \
+      localauthority x509 show -output json | jq -r .active.upstream_authority_subject_key_id) || fail-now "Failed to fetch old upstrem authority ID"
 
-agents=("root-agent" "intermediateA-agent" "intermediateB-agent" "leafA-agent" "leafB-agent")
-for agent in "${agents[@]}"; do
-    validate-agent "$agent"
-    check_ski "$agent" "$active_authority"
-done
+log-debug "Active upstream authority: $activeUpstreamAuthority"
+
+validate-agent spire-agent 
+check_ski spire-agent "$activeUpstreamAuthority"
+
