some normalization
Signed-off-by: Marcos Yacob <marcosyacob@gmail.com>

diff --git a/test/integration/suites/force-rotation-self-signed/12-taint-x509authority b/test/integration/suites/force-rotation-self-signed/12-taint-x509authority
--- a/test/integration/suites/force-rotation-self-signed/12-taint-x509authority
+++ b/test/integration/suites/force-rotation-self-signed/12-taint-x509authority
@@ -3,100 +3,69 @@
 NUMCHECKS=15
 CHECKINTERVAL=2
 
-verifyX509SVID() {
-      local agent=$1
-      local expectedAuthority=$2
-
-      for ((i=1;i<=NUMCHECKS;i++)); do
-        log-info "checking for SVID rotation ok $agent ($i of $MAXCHECKS max)..."
-        # Write svid on disk
-        docker compose exec -u 1001 -T $agent \
-              /opt/spire/bin/spire-agent api fetch x509 \
-              -socketPath /opt/spire/sockets/workload_api.sock \
-              -write /tmp || fail-now "x509-SVID check failed"
-
-        # Copy SVID
-        docker cp $(docker compose ps -q $1):/tmp/svid.0.pem - | docker cp - $(docker compose ps -q $2):/opt/
-
-        docker compose exec -u 1001 -T $2 \
-              /opt/spire/bin/spire-agent api fetch x509 \
-              -socketPath /opt/spire/sockets/workload_api.sock \
-              -write /tmp || fail-now "x509-SVID check failed"
-
-        docker compose exec -T $2 openssl verify -verbose -CAfile /tmp/bundle.0.pem -untrusted /opt/svid.0.pem /opt/svid.0.pem
-
-        sleep "${CHECKINTERVAL}"
-    done
+check-logs() {
+  local component=$1
+  shift
+  for log in "$@"; do
+        check-log-line "$component" "$log"
+  done
 }
-
-
-# Function to check log lines
-check_logs() {
-      local component=$1
-      shift
-      for log in "$@"; do
-            check-log-line ${component} "${log}"
-      done
-}
-
 
 # Fetch old authority ID
 oldAuthority=$(docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
       /opt/spire/bin/spire-server \
-      localauthority x509 show -output json | jq .old.authority_id -r)
+      localauthority x509 show -output json | jq .old.authority_id -r) || fail-now "Failed to fetch old authority ID"
 
 # Taint the old authority
 docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
       /opt/spire/bin/spire-server \
-      localauthority x509 taint -authorityID ${oldAuthority} -output json | jq .tainted_authority.authority_id
+      localauthority x509 taint -authorityID "${oldAuthority}" -output json | jq .tainted_authority.authority_id || fail-now "Failed to taint old authority"
 
 # Root server logs
-check_logs root-server \
+check-logs root-server \
       "X\.509 authority tainted successfully|local_authority_id=${oldAuthority}" \
       "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
 
 # Root agent logs
-check_logs root-agent \
+check-logs root-agent \
       "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
       "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=3" \
       "Agent SVID is tainted by a root authority, forcing rotation"
 
-
 # Verify workloads are rotated
 
 # Intermediate A server and agent logs
-check_logs intermediateA-server \
+check-logs intermediateA-server \
       "Current root CA is signed by a tainted upstream authority, preparing rotation" \
       "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
-check_logs intermediateA-agent \
-      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
-      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=2" \
-      "Agent SVID is tainted by a root authority, forcing rotation"
-
-# Intermediate B server and agent logs
-check_logs intermediateB-server \
-      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
-      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
-check_logs intermediateB-agent \
-      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
+check-logs intermediateA-agent \
+      "New tainted X\.509 authorities found|subject_key_ids=${oldAuthority}" \
       "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=2" \
       "Agent SVID is tainted by a root authority, forcing rotation"
 
-# Leaf A server and agent logs
-check_logs leafA-server \
+# Intermediate B server and agent logs
+check-logs intermediateB-server \
       "Current root CA is signed by a tainted upstream authority, preparing rotation" \
       "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
-check_logs leafA-agent \
+check-logs intermediateB-agent \
+      "New tainted X\.509 authorities found|subject_key_ids=${oldAuthority}" \
+      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=2" \
+      "Agent SVID is tainted by a root authority, forcing rotation"
+
+# Leaf A server and agent logs
+check-logs leafA-server \
+      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
+      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
+check-logs leafA-agent \
       "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
-      "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=1" \
+      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=1" \
       "Agent SVID is tainted by a root authority, forcing rotation"
 
 # Leaf B server and agent logs
-check_logs leafB-server \
+check-logs leafB-server \
       "Current root CA is signed by a tainted upstream authority, preparing rotation" \
       "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
-check_logs leafB-agent \
+check-logs leafB-agent \
       "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
-      "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=1" \
+      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=1" \
       "Agent SVID is tainted by a root authority, forcing rotation"
-
diff --git a/test/integration/suites/force-rotation-self-signed/13-verify-svids-rotates b/test/integration/suites/force-rotation-self-signed/13-verify-svids-rotates
--- a/test/integration/suites/force-rotation-self-signed/13-verify-svids-rotates
+++ b/test/integration/suites/force-rotation-self-signed/13-verify-svids-rotates
@@ -3,40 +3,43 @@
 MAX_RETRIES=10
 RETRY_DELAY=2 # seconds between retries
 
-check_tainted_authorities() {
+fetch-x509-authorities() {
+    local server=$1
+    docker compose exec -T "$server" /opt/spire/bin/spire-server bundle show -output json | jq .x509_authorities
+}
+
+verify-svid() {
+    local agent=$1
+    local agent_dir=$2
+
+    docker compose exec -u 1001 -T "$agent" \
+        /opt/spire/bin/spire-agent api fetch x509 \
+        -socketPath /opt/spire/sockets/workload_api.sock \
+        -write /tmp || fail-now "x509-SVID check failed for $agent"
+
+    docker compose exec -T "$agent" \
+        openssl verify -verbose -CAfile /opt/spire/conf/agent/non-tainted.pem \
+        -untrusted /tmp/svid.0.pem /tmp/svid.0.pem
+}
+
+check-tainted-authorities() {
     local server=$1
     local agent=$2
     local agent_dir=$3
 
-    x509Authorities=$(docker compose exec -T "$server" \
-        /opt/spire/bin/spire-server \
-        bundle show -output json | jq .x509_authorities)
+    x509Authorities=$(fetch-x509-authorities "$server")
 
-    taintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == true)')
-    if [[ -z "$taintedFound" ]]; then
-        fail-now "Tainted authority expected"
-    fi
+    taintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == true)') || fail-now "Tainted authority not found"
 
-    nonTaintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == false)')
-    if [[ -z "$nonTaintedFound" ]]; then
-        fail-now "Non-tainted authority expected"
-    fi
+    nonTaintedFound=$(echo "$x509Authorities" | jq '.[] | select(.tainted == false)') || fail-now "Non-tainted authority not found"
 
     echo "$nonTaintedFound" | jq -r .asn1 | base64 -d | openssl x509 -inform der > "$agent_dir/agent/non-tainted.pem"
 
     RETRY_COUNT=0
 
     while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
-        docker compose exec -u 1001 -T "$agent" \
-          /opt/spire/bin/spire-agent api fetch x509 \
-          -socketPath /opt/spire/sockets/workload_api.sock \
-          -write /tmp || fail-now "x509-SVID check failed for $agent"
+        verify-svid "$agent" "$agent_dir"
 
-        docker compose exec -T "$agent" \
-            openssl verify -verbose -CAfile /opt/spire/conf/agent/non-tainted.pem \
-            -untrusted /tmp/svid.0.pem /tmp/svid.0.pem
-
-        # Check the exit status of the verify command
         if [ $? -eq 0 ]; then
             log-info "SVID rotated"
             break
@@ -46,7 +49,6 @@ check_tainted_authorities() {
             sleep $RETRY_DELAY
         fi
 
-        # Fail if retries exceed the maximum
         if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
             fail-now "Certificate verification failed after $MAX_RETRIES attempts."
         fi
@@ -54,17 +56,16 @@ check_tainted_authorities() {
 }
 
 # Root
-check_tainted_authorities "root-server" "root-agent" "root"
+check-tainted-authorities "root-server" "root-agent" "root"
 
 # IntermediateA
-check_tainted_authorities "intermediateA-server" "intermediateA-agent" "intermediateA"
+check-tainted-authorities "intermediateA-server" "intermediateA-agent" "intermediateA"
 
 # IntermediateB
-check_tainted_authorities "intermediateB-server" "intermediateB-agent" "intermediateB"
+check-tainted-authorities "intermediateB-server" "intermediateB-agent" "intermediateB"
 
 # LeafA
-check_tainted_authorities "leafA-server" "leafA-agent" "leafA"
+check-tainted-authorities "leafA-server" "leafA-agent" "leafA"
 
 # LeafB
-check_tainted_authorities "leafB-server" "leafB-agent" "leafB"
-
+check-tainted-authorities "leafB-server" "leafB-agent" "leafB"
diff --git a/test/integration/suites/force-rotation-self-signed/15-verify-revoked-x509authority b/test/integration/suites/force-rotation-self-signed/15-verify-revoked-x509authority
--- a/test/integration/suites/force-rotation-self-signed/15-verify-revoked-x509authority
+++ b/test/integration/suites/force-rotation-self-signed/15-verify-revoked-x509authority
@@ -3,46 +3,59 @@
 MAX_RETRIES=10
 RETRY_DELAY=2 # seconds between retries
 
-oldAuthority=$(docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
-    /opt/spire/bin/spire-server \
-    localauthority x509 show -output json | jq .active.authority_id -r)
-log-debug "Revoked authority: $oldAuthority"
+fetch-old-authority() {
+    docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
+        /opt/spire/bin/spire-server localauthority x509 show -output json | jq .active.authority_id -r
+}
+
+validate-agent() {
+    local agent=$1
+    local retry_count=0
+
+    while [[ $retry_count -lt $MAX_RETRIES ]]; do
+        docker compose exec -u 1001 -T $agent \
+            /opt/spire/bin/spire-agent api fetch x509 \
+            -socketPath /opt/spire/sockets/workload_api.sock \
+            -write /tmp || fail_now "x509-SVID check failed for $agent"
+
+        local bundle_count=$(docker compose exec -T $agent \
+            openssl storeutl -noout -text -certs /tmp/bundle.0.pem | grep -c "Certificate:")
+        if [ $bundle_count -eq 1 ]; then
+            log-debug "Validation successful for $agent: There is exactly one certificate in the chain."
+            return 0
+        else
+            log-debug "Validation failed for $agent: Expected 1 certificate, but found $bundle_count. Retrying in $RETRY_DELAY seconds... ($retry_count/$MAX_RETRIES)"
+        fi
+
+        retry_count=$((retry_count + 1))
+        sleep $RETRY_DELAY
+
+        if [ $retry_count -eq $MAX_RETRIES ]; then
+            fail-now "Validation failed for $agent: Expected 1 certificate, but found $bundle_count."
+        fi
+    done
+}
+
+check_ski() {
+    local agent=$1
+    local old_authority=$2
+
+    local ski=$(docker compose exec -T $agent \
+	    openssl x509 -in /tmp/bundle.0.pem -text | grep \
+	    -A 1 'Subject Key Identifier' | tail -n 1 | tr -d ' ' | tr -d ':' | tr '[:upper:]' '[:lower:]')
+
+    if [ "$ski" == "$old_authority" ]; then
+        log-debug "Subject Key Identifier matches for $agent: $ski"
+    else
+        fail-now "Subject Key Identifier does not match for $agent. Found: $ski Expected: $old_authority"
+    fi
+}
+
+old_authority=$(fetch-old-authority)
+log-debug "Revoked authority: $old_authority"
 
 agents=("root-agent" "intermediateA-agent" "intermediateB-agent" "leafA-agent" "leafB-agent")
 for agent in "${agents[@]}"; do
-    RETRY_COUNT=0
-    while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
-        if docker compose exec -u 1001 -T $agent \
-          /opt/spire/bin/spire-agent api fetch x509 \
-          -socketPath /opt/spire/sockets/workload_api.sock \
-          -write /tmp; then
-
-            bundleCount=$(docker compose exec -T $agent \
-		    openssl storeutl -noout -text -certs /tmp/bundle.0.pem | grep -c "Certificate:")
-            if [ $bundleCount -eq 1 ]; then
-                log-debug "Validation successful for $agent: There is exactly one certificate in the chain."
-                break
-            else
-                log-debug "Validation failed for $agent: Expected 1 certificate, but found $bundleCount. Retrying in $RETRY_DELAY seconds... ($RETRY_COUNT/$MAX_RETRIES)"
-            fi
-        else
-            fail-now "x509-SVID check failed for $agent"
-        fi
-
-        RETRY_COUNT=$((RETRY_COUNT + 1))
-        sleep $RETRY_DELAY
-
-        # Fail if retries exceed the maximum
-        if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
-            fail-now "Validation failed for $agent: Expected 1 certificate, but found $bundleCount."
-        fi
-    done
-
-    ski=$(docker compose exec -T $agent openssl x509 -in /tmp/bundle.0.pem -text | grep -A 1 'Subject Key Identifier' | tail -n 1 | tr -d ' ' | tr -d ':' | tr '[:upper:]' '[:lower:]')
-
-    if [ "$ski" == "$oldAuthority" ]; then
-        log-debug "Subject Key Identifier matches for $agent: $ski"
-    else
-        fail-now "Subject Key Identifier does not match for $agent. Found: $ski Expected: $oldAuthority"
-    fi
+    validate-agent "$agent"
+    check_ski "$agent" "$old_authority"
 done
